service: serverlessSetupSamiJNodeLeraning

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

# functions
functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http: 
          path: serverlessSetupSamiJNodeLeraning/hello
          method: get
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http: 
          path: serverlessSetupSamiJNodeLeraning/goodbye
          method: post
  question:
    handler: src/functions/question.handler
    dependsOn: SNSHelloEvent
    events:
      - sns:
          arn: !Ref SNSHelloEvent
          topicName: hello-event
  
  vivantis-scraper:
    handler: src/functions/vivantis-scraper.handler
    timeout: 6000
    events:
      - http:
          path: serverlessSetupSamiJNodeLeraning/vivantis-scraper
          method: get

# Serverless plugins
plugins:
  - serverless-offline

